Users crud V3
Educado-App/educado-frontend pull request #172
Opened 2024-10-30 09:52 UTC by LazarShockX

Again

2024-10-30 12:27 UTC, LazarShockX reviewed
Merge successful 🩵

2024-10-30 13:30 UTC, LazarShockX commented
<img width="840" alt="Screenshot 2024-10-30 at 14 26 45" src="https://github.com/user-attachments/assets/38bf9867-8b17-46ee-bd88-a4a4dc934fdd">
<img width="1355" alt="Screenshot 2024-10-30 at 14 30 06" src="https://github.com/user-attachments/assets/27fd8742-a279-4c22-a410-0765d1d22c3c">

The 2 failing Cypress Tests are incorrect, since the application overview page correctly shows a list of applicants and the search term works.

2024-10-30 15:53 UTC, madsWesth approved these changes

2024-10-31 22:27 UTC, LazarShockX commented
En gruppe syntes det var sjovt at flytte Navbar til app/src/components/navbar/Navbar.tsx, så nu har vi en ny fucking merge konflikt

2024-11-01 09:05 UTC, Laskiri requested changes
Remove the redundant path, and AdminProtect the others as i've described on the app.tsx file. Additionally take a look at my other suggestions if you're not to stressed with other things, else its small fixes that can be handled in the future.

2024-11-01 09:05 UTC, Laskiri commented on app/src/services/auth.guard.ts
I would suggest, making a variable isAdmin = userRole === requiredRole, and use that in your logical expressions for better readability if it's not to much work ^^,

2024-11-01 09:33 UTC, Laskiri commented
> En gruppe syntes det var sjovt at flytte Navbar til app/src/components/navbar/Navbar.tsx, så nu har vi en ny fucking merge konflikt og det værste er, at jeg ikke engang kan fikse det i web editoren

sig til hvis du får brug for hjælp til dette

2024-11-01 09:37 UTC, LazarShockX commented
> > En gruppe syntes det var sjovt at flytte Navbar til app/src/components/navbar/Navbar.tsx, så nu har vi en ny fucking merge konflikt og det værste er, at jeg ikke engang kan fikse det i web editoren
> 
> sig til hvis du får brug for hjælp til dette

Meget gerne 🩵 for når jeg prøver at løse det, opstår der 42 andre konflikter
<img width="358" alt="Screenshot 2024-11-01 at 10 36 26" src="https://github.com/user-attachments/assets/28865168-661b-4658-99e9-be23ba83e486">

2024-11-01 09:38 UTC, Todua992 approved these changes
Honestly it looks good, Nice touch with UI. And yeah, I agree with Lasse about the Request change he made. The rest of the code seems to work, and doesnt break application. So nice work with that.

2024-11-03 12:25 UTC, LazarShockX commented
> Remove the redundant path, and AdminProtect the others as i've described on the app.tsx file. Additionally take a look at my other suggestions if you're not to stressed with other things, else its small fixes that can be handled in the future.

I will look into your suggestions for the next sprint. Right now I just want to merge it 🩵

2024-11-03 12:25 UTC, merged

2024-11-03 12:48 UTC, LazarShockX commented
Det er helt væk. Den har ikke merget usersCrud ind i dev.

2024-11-04 11:25 UTC, Laskiri commented
> > Remove the redundant path, and AdminProtect the others as i've described on the app.tsx file. Additionally take a look at my other suggestions if you're not to stressed with other things, else its small fixes that can be handled in the future.
> 
> I will look into your suggestions for the next sprint. Right now I just want to merge it 🩵

No worries, as i said most if it was minor things for better quality and readabily, however the AdminProtectedRoutes must be integrated properly with the different paths. Good job with this pbi guys, i know it was really large but you got around with it 💪