VT bucket merge
Educado-App/educado-frontend pull request #56
Opened 2023-11-22 09:28 UTC by magnemo

## Description

Made buckets work on the front end. 
Made the commponts array on the the setions to contain the lectures and execises 

## Changes
Updated storage.services to work with google buckets 
Add bucket service and supporting code to the files CreateCourseModal, CreateLecturePopUp, CourseEdit
Fixed spam create bug CreateLecturePopUp and CreateExercisePopUp
Made the create button to a commponet
Simplified the Dropzone  commponet

## Checklist

- [ ] Code has been tested locally and passes all relevant tests.
- [ ] Documentation has been updated to reflect the changes, if applicable.
- [ ] Code follows the established coding style and guidelines of the project.
- [ ] All new and existing tests related to the changes have passed.
- [ ] Any necessary dependencies or new packages have been properly documented.
- [ ] Pull request title and description are clear and descriptive.
- [ ] Reviewers have been assigned to the pull request.
- [ ] Any potential security implications have been considered and addressed.
- [ ] Performance impact of the changes has been evaluated, if relevant.

2023-11-22 10:41 UTC, TheMOHD3886 approved these changes
Looks sinds fellas, 10/10 code 👍

2023-11-22 11:41 UTC, JackSMunn requested changes

2023-11-22 11:42 UTC, JackSMunn commented
Just address the comments and i will approve.

2023-11-22 12:07 UTC, magnemo commented on app/src/pages/CourseEdit.tsx
> +  coverImg?: string
The ? allows for the value to not be set, we did this as, it is not a required field in the db

2023-11-23 08:53 UTC, Jatewo approved these changes
### Looks good to me 👍

2023-11-23 08:53 UTC, Jatewo commented on app/src/components/CreateButtonCompont.tsx
> +                <label htmlFor='lecture-create' className=" bg-primary hover:bg-primaryHover border border-primary focus:ring-blue-500 focus:ring-offset-blue-200 text-white w-full transition ease-in
It rather seems like you could make a custom class with these to avoid the long line but I wouldn't say that's crucial.

2023-11-23 08:53 UTC, Jatewo commented on app/src/pages/CourseEdit.tsx
> +  coverImg?: string
I think the question was why the type is a string. But I assume it's a path to the img?

2023-11-23 08:58 UTC, magnemo commented on app/src/pages/CourseEdit.tsx
> +  coverImg?: string
Yes Jatewo, it is the refers to the id used to find it in the google buckets

2023-11-23 10:36 UTC, JackSMunn approved these changes

2023-11-23 11:33 UTC, merged